name: Atualizando imagem do Kubernetes no Linode

on:
  pull_request:
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Configurar o ambiente do Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker build, push e Kubernetes apply
        run: |
          docker build -t claudiocassimiro/products-api:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push claudiocassimiro/products-api:latest
          kubectl apply -f k8s.yaml
