name: Atualizando imagem do Kubernetes no Linode

on:
  pull_request:
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Install the Linode CLI
        uses: linode/action-linode-cli@v1
        with:
          token: ${{ secrets.LINODE_TOKEN }}

      - name: Configurar o ambiente do Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker build e push
        run: |
          docker build -t claudiocassimiro/products-api:latest .
          docker push claudiocassimiro/products-api:latest

      - name: Atualizar imagem no Kubernetes no Linode
        run: |
          linode-cli lke cluster kubeconfig view --kubeconfig kubeconfig.yaml --cluster-id lke117125
          export KUBECONFIG=kubeconfig.yaml
          kubectl set image deployment/products-api products-api=claudiocassimiro/products-api:latest
